version: "3"

services:
  db:
    image: postgres:14.0
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minesweeper
    ports:
      - "5432:5432"
